### ISSUE TITLE
not replacing the token when js file is minified

### ISSUE THREAD

**Issue by graphicsxp** [solidify/vsts-task-tokenize-in-archive#5]
We have a javascript file called main.js. The tokens in this files are replaced by the plugin.

But if we minify the code inside this file and we rename it to main.e329d6fedce16d5bcefe.js , then the tokens are not replaced. There is nothing in the log file, other than the fact that the file  was found :

Searching for all *.zip files at f:\_work\r4\a\eCdT-Evolution\drop\
Searching for main.*.js inside *.zip files

Matched zip: F:\_work\r4\a\eCdT-Evolution\drop\
Matched file in zip: main.e329d6fedce16d5bcefe.js

Finishing: Tokenize myProject.zip

Any idea what could cause the plugin to fail ?

**Comment by graphicsxp** [comment]
I forgot to mention that in the task definition we specify the name of the file like this :  main.*.js

the wildcard could be a problem ?

**Comment by graphicsxp** [comment]
sorry my bad. The name of the file should be "main."  as the powershell uses regular expression.

**Comment by MOlausson** [comment]
Great to hear it worked ut @graphicsxp and thanks for engaging.
